# Generated by Django 4.1.3 on 2023-01-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='dataAtualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
